### ISSUE TITLE
Get Documentation `MethodInfo` Bug Fix

### ISSUE THREAD

**Issue by ZacharyPatten** [swharden/Washcloth#1]
I just fixed a bug in them in [Towel](https://github.com/ZacharyPatten/Towel), so you probably want to apply the same bug fix to your copy.

Bug Report Issue: https://github.com/ZacharyPatten/Towel/issues/52
Bug Fix: https://github.com/ZacharyPatten/Towel/commit/afddb2fef8d749338608f98754a4257fdafbcb8d

All you need to do is add this check to the `MethodInfo` overload:
```cs
if (methodInfo is not null && methodInfo.DeclaringType!.IsGenericType)
{
	methodInfo = methodInfo.DeclaringType.GetGenericTypeDefinition().GetMethods().First(x => x.MetadataToken == methodInfo.MetadataToken);
}
```

**Comment by swharden** [comment]
Fixed (620d74c5adc7f93c231d3d5def2a9c67fe36e65c) - Thanks @ZacharyPatten!
